CREATE DATABASE SmartExchange;
USE SmartExchange;

CREATE TABLE Users (
    userId UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(80) NOT NULL,
    fullName NVARCHAR(100) NOT NULL,
    jobTitle NVARCHAR(100),
	languageCode VARCHAR(3) CHECK (languageCode IN ('vi','jp')) DEFAULT 'jp',
	themeMode VARCHAR(7) CHECK (themeMode IN ('light','dark')) DEFAULT 'light',
	isTutorialCompleted BIT NOT NULL DEFAULT 0,
    createdAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Chat (
    chatId UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY NOT NULL,
    userOneId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(userId),
    userTwoId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(userId),
    updateAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT CHK_UserOrder CHECK (userOneId < userTwoId),
    CONSTRAINT UQ_ConversationPair UNIQUE (userOneId, userTwoId)
);
CREATE NONCLUSTERED INDEX IDX_Chat_UserOne_Sort ON Chat(userOneId, updateAt DESC) INCLUDE (userTwoId); 
CREATE NONCLUSTERED INDEX IDX_Chat_UserTwo_Sort ON Chat(userTwoId, updateAt DESC) INCLUDE (userOneId);

CREATE TABLE Messages (
    messageId UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY NOT NULL,
    chatId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Chat(chatId) ON DELETE CASCADE,
    senderId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(userId),
    content NVARCHAR(MAX),
	aiAnalysisContent NVARCHAR(MAX),
    createdAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    isRead BIT DEFAULT 0
);
CREATE NONCLUSTERED INDEX IDX_Messages_GetContent ON Messages(chatId, createdAt DESC) INCLUDE (senderId, isRead, messageId);